### ISSUE TITLE
Compatibility issues with optifine

### ISSUE THREAD

**Issue by Karpatok9089** [mineLdiver/GLSL#1]
Cannot load properly with optifine. The screen doesn't shows the OpenGL info correctly. Also, the game after 2 minutes just crashes.
![2024-02-18_19 16 55](https://github.com/mineLdiver/Macula/assets/110969697/77259c98-72ed-4994-b2bf-b39e23b25c20)

**Comment by mineLdiver** [comment]
The crashlog would be useful.

The OpenGL information being null is known and, as far as I know, there isn't much I can do about it because, from what I understand, OptiFine pulls that information earlier, leaving Macula with null.

**Comment by Karpatok9089** [comment]
Okay i already figured it out that the problem is STATUS_STACK_BUFFER_OVERRUN, and I did resolve it.
