### ISSUE TITLE
[Suggestion] Water shader support

### ISSUE THREAD

**Issue by Karpatok9089** [mineLdiver/GLSL#4]
Add watershader support to Macula Shaders. It should work like this:

1 The game locates the files inside the .minecraft/watershd folder
2 When the shaders are inactive, its just loads the Watershaders as normal. When a shaderpack's present, itt adds as a shader alongside the shaderpack. If it fails. It will disable itself
The watershader's optional and can be disabled at the shaderpack menu
Currently the only way to add shaders is to load the with optifine and its incompatibe with macula

![2024-03-08_13 57 00](https://github.com/mineLdiver/Macula/assets/110969697/0e81d577-401b-4d2c-93d9-72da59f4292c)
A concept how it would look like. It's not exactly how it should work because in reality, this is an image on top of another image, so the water reflection has no shaders.

**Comment by mineLdiver** [comment]
OptiFine is compatible with Macula via OptiBabric, but I'm not sure what you mean by loading shaders with OptiFine? Last I checked, OptiFine on b1.7.3 has no mention of shaders anywhere.

**Comment by Karpatok9089** [comment]
I meant the only way to load WaterShaders mod is to mod the optifine zip file, and load it with optibabric. Optifine is compatible with it but the optifine+watershaders don't.
